---
- hosts: all
  sudo: yes
  tasks:
    - name: Install python-pycurl
      apt: name=python-pycurl
    - name: Download ArangoDB pregel build
      get_url: url=http://test.arangodb.org/sinnlos/arangodb_2.4d_amd64.deb dest=/var/cache/apt/arangodb_2.4d_amd64.deb sha256sum=9ad434bb359d053211de1573fb012bbeb95b3cfbe07ff8de853f63c7e5a52764
    - name: Install ArangoDB from file
      shell: dpkg -i arangodb_2.4d_amd64.deb chdir=/var/cache/apt/
    - pause: seconds=5
    - name: Stop arangodb
      service: name=arangodb state=stopped
    - pause: seconds=5
    - name: Create dispatcher config
      template: src=templates/arangod.dispatcher.conf.j2 dest=/etc/arangodb/arangod.conf
      notify: restart arangodb
    - name: Create single-config
      template: src=templates/arangod.single.conf.j2 dest=/etc/arangodb/arangod.single.conf
  handlers:
    - name: restart arangodb
      service: name=arangodb state=restarted
