---
- hosts: all
  sudo: yes
  tasks:
    - name: add arangodb key
      apt_key: url=https://www.arangodb.org/repositories/arangodb2/xUbuntu_12.04/Release.key state=present
    - name: add arangodb repo
      apt_repository: repo='deb https://www.arangodb.org/repositories/arangodb2/xUbuntu_12.04 /' state=present
    - name: install arangodb
      apt: name=arangodb=2.2.2 update_cache=yes