---
- hosts: all
  sudo: yes
  tasks:
    - name: Install python-pycurl
      apt: name=python-pycurl
    - name: Add arangodb key
      apt_key: url=https://www.arangodb.org/repositories/arangodb2/xUbuntu_12.04/Release.key state=present
    - name: Add arangodb repo
      apt_repository: repo='deb https://www.arangodb.org/repositories/arangodb2/xUbuntu_12.04 /' state=present
    - name: Install arangodb
      apt: name=arangodb=2.2.2 update_cache=yes
    - name: Start up arangodb
      service: name=arangodb state=stopped
    - name: Create dispatcher config
      template: src=templates/arangod.dispatcher.conf.j2 dest=/etc/arangodb/arangod.conf
      notify: restart arangodb
    - name: Create single-config
      template: src=templates/arangod.single.conf.j2 dest=/etc/arangodb/arangod.single.conf
  handlers:
    - name: restart arangodb
      service: name=arangodb state=restarted
