---
- hosts: all
  sudo: yes
  tasks:
    - name: add arangodb key
      apt_key: url=https://www.arangodb.org/repositories/arangodb2/xUbuntu_12.04/Release.key state=present
    - name: add arangodb repo
      apt_repository: repo='deb https://www.arangodb.org/repositories/arangodb2/xUbuntu_12.04 /' state=present
    - name: install arangodb
      apt: name=arangodb=2.2.2 update_cache=yes
    - name: Create a cluster Config file
      template: src=templates/arangod.dispatcher.conf.j2 dest=/etc/arangodb/arangod.conf
    - name: enable dispatcher kickstarter
      ini_file: dest=/etc/anotherconf
                section=dispatcher
                option=disable-dispatcher-kickstarter
                value=no
      notify:
      - restart arangodb
    - name: enable dispatcher frontend
      ini_file: dest=/etc/anotherconf
                section=dispatcher
                option=disable-dispatcher-frontend
                value=no
      notify:
      - restart arangodb
    - name: ensure arangodb is running
      service: name=arangodb state=started
  handlers:
    - name: restart arangodb
      service: name=arangodb state=restarted